// ============================================================
// Demo content for scripts/seedTravelDemo.js
//
// Five destinations, each with:
//   blog     the article (HTML is built from these fields)
//   basic    Travel Guide items unlocked by the Basic plan   (rank 1, Rs 49)
//   premium  items that need Premium or above                (rank 2, Rs 99)
//   ultimate items that need Ultimate                        (rank 3, Rs 159)
//   rates    rate-card rows: [tier, service, price, unit, notes]
//
// Items are [category, title, body, contact?]. Categories come from data/travelCategories.js.
// All prices are approximate 2026 figures in rupees and are illustrative test data:
// verify before publishing. No phone numbers are invented; "contact" says how to book.
// ============================================================

module.exports = [
  // ──────────────────────────────────────────────────────────
  {
    slug: "kerala",
    title: "Kerala",
    location: "Kerala, India",
    summary: "Backwaters, tea hills, beaches and Ayurveda: a week in God's Own Country.",
    cover: "/uploads/travel-kerala.jpg",
    blog: {
      title: "Kerala – Explore God's Own Country",
      sub: "Beach & Islands",
      heading: "1. Kerala – Explore God's Own Country",
      intro: "Kerala packs coastline, lagoons, spice-scented hills and colonial ports into a narrow strip along India's south-west edge. Drift through the Alleppey backwaters, wake up above the tea gardens of Munnar and end the week on the red cliffs of Varkala.",
      about: "Kerala's best season is October to March, when it is dry and cool. The monsoon (June to September) turns everything green and cuts prices sharply, but boat rides and hill roads can be disrupted. Malayalam is the main language, English is widely understood, and the state is one of the easiest in India for first-time travellers.",
      places: [
        ["Fort Kochi", "Chinese fishing nets, Mattancherry's Jew Town, Santa Cruz Basilica and the evening Kathakali shows."],
        ["Alleppey (Alappuzha) backwaters", "Houseboats, canoe rides and village life along the canals of Kuttanad."],
        ["Munnar", "Rolling tea estates, Eravikulam National Park and the Mattupetty dam viewpoints."],
        ["Thekkady (Periyar)", "Spice plantations, bamboo rafting and a boat safari on Periyar Lake."],
        ["Varkala", "A cliff-top beach town with sunset cafes and the Janardhana Swamy temple."],
      ],
      reach: [
        "By air: Cochin International (COK) is the main gateway; Thiruvananthapuram (TRV) and Calicut (CCJ) serve the south and north.",
        "By train: Ernakulam Junction (ERS) and Thiruvananthapuram Central (TVC) are on direct lines from Chennai, Bengaluru, Mumbai (via the Konkan line) and Delhi.",
        "By road: Overnight KSRTC and private sleeper buses run from Bengaluru, Chennai and Coimbatore.",
      ],
      expenses: [
        "Budget traveller: about ₹1,800 to ₹2,200 per day (hostel or homestay, public transport, local meals).",
        "Comfortable traveller: about ₹4,500 to ₹6,500 per day (good homestay, cab or scooter, restaurant meals).",
        "A private houseboat is a splurge: roughly ₹9,000 to ₹16,000 per night for two.",
      ],
      tips: [
        "Book houseboats through the tourism department or a well-reviewed operator, not from touts at the jetty.",
        "Carry a light rain jacket even in winter on the Munnar road.",
        "Dress modestly at temples; men may be asked to remove shirts at some of them.",
        "Book Kochi to Munnar early on weekends: the hill road fills up fast.",
      ],
    },
    basic: [
      ["how_to_reach", "Reaching Kerala on a budget", "Trains are the cheapest way in. Sleeper class from Bengaluru or Chennai to Ernakulam Junction costs roughly ₹450 to ₹700; 3AC is about ₹1,200 to ₹1,800. Book 60 to 120 days ahead on IRCTC for weekends and festival dates. From the north, the Kerala Express and Rajdhani-type services take 36 to 48 hours."],
      ["bus", "Buses between the main stops", "KSRTC and private buses connect all the popular stops: Kochi to Alleppey about ₹70 to ₹110 (1.5 to 2 hours); Kochi to Munnar about ₹180 to ₹260 (4 to 5 hours); Munnar to Thekkady about ₹120 to ₹170 (4 hours). Buses leave from the KSRTC stand in Ernakulam and the Alleppey main bus stand."],
      ["train", "Trains along the coast", "Ernakulam to Alleppey has frequent passenger and express trains for ₹30 to ₹90 (about 1.5 hours). Thiruvananthapuram to Varkala takes 40 minutes and costs under ₹40 in general class."],
      ["places", "Free and cheap sights", "Fort Kochi walk (free), Mattancherry Palace (small entry fee), Alleppey beach at sunset (free), Varkala cliff and Papanasam beach (free), Eravikulam National Park in Munnar (a few hundred rupees entry). The Alleppey to Kottayam public ferry (about ₹30) is the cheapest backwater ride."],
      ["expenses", "Basic expense estimate", "Five days on a tight budget, per person: transport ₹2,500 to ₹3,500, stay ₹2,500 to ₹3,500 (hostel or basic lodge at ₹500 to ₹800 a night), food ₹1,500 to ₹2,000, entry fees and ferries ₹700. Total roughly ₹8,000 to ₹11,000."],
      ["itinerary", "Basic 5-day itinerary", "Day 1: Arrive in Kochi, walk Fort Kochi and the fishing nets.\nDay 2: Train to Alleppey, public ferry ride, sunset at the beach.\nDay 3: Bus to Munnar, tea garden walk.\nDay 4: Eravikulam National Park and Mattupetty viewpoint.\nDay 5: Bus back to Kochi and onward travel."],
      ["other", "Budget travel tips", "Eat 'meals' (rice with curries) at local restaurants for ₹80 to ₹150. Use the state-run ferries. Travel on weekdays: lodges and buses cost less. Carry a refillable bottle; most homestays provide filtered water."],
    ],
    premium: [
      ["hotel", "Better stays: homestays and mid-range resorts", "Fort Kochi heritage homestays run ₹2,800 to ₹4,500 a night with breakfast. Alleppey lakeside homestays: ₹2,500 to ₹4,000. Munnar plantation resorts: ₹3,500 to ₹6,500. Choose a homestay with a host who cooks: home-style Kerala breakfasts are a highlight."],
      ["bike_rental", "Scooter and bike rental", "Scooters (Activa-type) rent for ₹400 to ₹700 a day in Kochi, Munnar and Varkala; Royal Enfield 350cc about ₹1,000 to ₹1,500. Carry a licence and ID; deposits are ₹1,500 to ₹3,000. Munnar's hill roads are steep with tight curves: ride in daylight."],
      ["local_transport", "Driving in Kerala: car information", "Kochi to Munnar is about 130 km (4 to 5 hours) via NH85; expect ghat curves after Adimali. Fuel up before the hills. Free roadside parking is limited in Fort Kochi: use the paid lots. Kochi to Alleppey via NH66 is about 55 km (1.5 hours) with light tolls."],
      ["restaurant", "Better restaurants and what to order", "Try a banana-leaf sadya, karimeen pollichathu (pearl-spot fish) in Alleppey, appam with stew, and Malabar-style biryani. A sit-down meal costs ₹300 to ₹600 a head. Fort Kochi has good cafes for breakfast and seafood shacks by the beach."],
      ["itinerary", "Detailed 5-day itinerary with timings", "Day 1: Land in Kochi, check in, 4 pm heritage walk, 6:30 pm Kathakali show (about ₹400).\nDay 2: 8 am drive to Alleppey, noon canoe ride, sunset at the beach.\nDay 3: 8 am drive to Munnar via Kottayam, tea museum, evening at the tea estate.\nDay 4: 7 am Eravikulam, Mattupetty, Echo Point.\nDay 5: Drive to Kochi with a stop at Cheeyappara waterfalls."],
      ["expenses", "Detailed estimate: comfortable trip", "Per person for 5 days: stay ₹9,000 to ₹13,000, scooter or cab ₹3,500 to ₹5,500, food ₹3,500 to ₹5,000, activities ₹2,000 to ₹3,000. Total roughly ₹16,000 to ₹22,000."],
      ["other", "Extra recommendations", "Kumarakom Bird Sanctuary at dawn; Athirappilly Falls on the way from Kochi to Munnar; an Ayurvedic massage at a certified centre (₹1,500 to ₹3,000 per session). Check the sunrise time and be at the viewpoint 30 minutes early."],
    ],
    ultimate: [
      ["flight", "Flights to Kerala", "Cochin (COK) is best for most trips. Typical one-way fares: Delhi ₹4,500 to ₹9,000, Mumbai ₹3,500 to ₹7,000, Bengaluru ₹2,500 to ₹5,000, Hyderabad ₹3,500 to ₹6,000. Book 3 to 4 weeks ahead. Kochi airport to Fort Kochi is about 28 km (₹900 to ₹1,300 by taxi). Fly into Thiruvananthapuram (TRV) if you begin in Varkala or Kovalam."],
      ["hotel", "Premium hotels and resorts", "Fort Kochi: Brunton Boatyard (heritage waterfront, about ₹9,000 to ₹16,000). Kochi: Taj Malabar Resort & Spa (Willingdon Island, about ₹9,000 to ₹15,000). Kumarakom: Kumarakom Lake Resort (about ₹14,000 to ₹30,000). Munnar luxury tea-estate villas: ₹10,000 to ₹25,000. Prices vary widely by season.", "Book on the property's official website."],
      ["car_rental", "Chauffeur-driven car rental", "Sedan (Dzire-type) with driver: ₹2,800 to ₹3,500 per day (about 250 km included). SUV (Innova-type): ₹4,500 to ₹6,500 a day. Airport pickup from Kochi adds about ₹300 to ₹500. Multi-day packages are cheaper per day. Ask the driver's licence and the vehicle's tourist permit.", "Book through a licensed tourist-taxi operator or your hotel."],
      ["guide", "Local and professional guides", "Kerala Tourism-approved guides: heritage walk in Fort Kochi ₹800 to ₹1,500; half-day Alleppey village tour ₹1,500 to ₹2,500; Munnar trekking guide (through DTPC/forest department) ₹1,000 to ₹2,000. Always ask for the accreditation card.", "Kerala Tourism / District Tourism Promotion Council offices."],
      ["restaurant", "Premium restaurants", "Fine dining in heritage properties, waterfront seafood tasting menus and chef-led Kerala thalis: ₹1,800 to ₹3,500 per person. Reserve dinners in Fort Kochi at least a day ahead in peak season."],
      ["itinerary", "Detailed 6-day luxury itinerary", "Day 1: Arrive Kochi, check in at a heritage hotel, sunset cruise.\nDay 2: Fort Kochi walk with a guide, lunch at a seafood restaurant, evening Kathakali.\nDay 3: Drive to Kumarakom, boat ride, bird sanctuary.\nDay 4: Board a private houseboat in Alleppey; overnight on the water.\nDay 5: Drive to Munnar, tea estate tour, plantation dinner.\nDay 6: Eravikulam sunrise, drive to Kochi, fly out."],
      ["expenses", "Complete trip cost (6 days, per person, from a metro)", "Return flight ₹8,000 to ₹16,000; hotels ₹40,000 to ₹65,000; houseboat share ₹5,000 to ₹8,000; car with driver ₹9,000 to ₹12,000; food ₹8,000 to ₹12,000; guides and activities ₹4,000 to ₹6,000. Total roughly ₹75,000 to ₹1,20,000."],
      ["other", "Premium recommendations", "Choose an AC houseboat with a separate dining deck and a cook who serves fresh fish. Book an Ayurveda retreat (3 to 7 nights) at an accredited 'Green Leaf' centre. Visit Athirappilly early to avoid crowds."],
    ],
    rates: [
      ["basic", "Bus: Kochi to Alleppey", 90, "per person", "State bus, about 1.5 to 2 hours"],
      ["basic", "Bus: Kochi to Munnar", 220, "per person", "KSRTC, about 4 to 5 hours"],
      ["basic", "Train: Bengaluru to Ernakulam (sleeper)", 550, "per person", "Overnight; book ahead"],
      ["basic", "Local auto-rickshaw", 60, "minimum fare", "Ask for the meter"],
      ["basic", "Kerala meals (rice + curries)", 120, "per meal", "Local restaurant"],
      ["premium", "Homestay (Fort Kochi)", 3500, "per night", "Breakfast included"],
      ["premium", "Scooter rental", 550, "per day", "Deposit and ID needed"],
      ["premium", "Royal Enfield rental", 1200, "per day", "Munnar and Varkala"],
      ["premium", "Seafood dinner for two", 1800, "for two", "Mid-range restaurant"],
      ["ultimate", "Flight: Bengaluru to Kochi", 3800, "one way", "Typical fare"],
      ["ultimate", "Premium hotel (Fort Kochi)", 12000, "per night", "Heritage waterfront"],
      ["ultimate", "Chauffeur-driven SUV", 5500, "per day", "About 250 km included"],
      ["ultimate", "Private houseboat (1 bedroom, AC)", 12000, "per night for two", "Meals included"],
      ["ultimate", "Accredited local guide", 2000, "per half-day", "Ask for the ID card"],
    ],
  },

  // ──────────────────────────────────────────────────────────
  {
    slug: "warangal-fort",
    title: "Warangal Fort",
    location: "Warangal, Telangana",
    summary: "The Kakatiya capital: a ruined fort, a thousand-pillar temple and a UNESCO World Heritage temple.",
    cover: "/uploads/travel-warangal.jpg",
    blog: {
      title: "Warangal – Explore The Ruins",
      sub: "Other",
      heading: "1. Warangal Fort – Explore The Ruins",
      intro: "Warangal was the capital of the Kakatiya dynasty (12th to 14th century). Today it is a quiet Telangana city where the ruins of a great fort, carved stone gateways and one of India's most graceful temples sit within an easy day trip of each other.",
      about: "Warangal is about 150 km from Hyderabad and is best visited between October and March. Summers are very hot. Two days cover the city and the temple at Palampet, and a third day adds a lake and forest getaway. Telugu and Urdu are widely spoken; Hindi and English work in most places.",
      places: [
        ["Warangal Fort", "The Kakatiya fort with its four great stone gateways (the Kakatiya Kala Thoranam), the Swayambhu temple ruins and a small museum."],
        ["Thousand Pillar Temple (Hanamkonda)", "A 12th-century Kakatiya temple with finely carved black basalt pillars and a monolithic Nandi."],
        ["Ramappa Temple (Palampet)", "UNESCO World Heritage temple (2021), famous for its light floating bricks and sculpted dancers. About 65 km from Warangal."],
        ["Bhadrakali Temple", "An ancient hilltop temple beside Bhadrakali Lake, lovely at sunset."],
        ["Laknavaram Lake", "A forest lake with boating and a suspension bridge, about 85 km away."],
      ],
      reach: [
        "By train: Warangal (WL) and Kazipet Junction (KZJ) are on the Delhi to Chennai trunk line. Hyderabad (Secunderabad) to Warangal takes about 2 to 2.5 hours.",
        "By road: Hyderabad to Warangal is about 150 km (3 hours) on the Hyderabad-Warangal highway. TSRTC runs frequent buses from Hyderabad's MGBS and Uppal.",
        "By air: The nearest major airport is Hyderabad (Rajiv Gandhi International), about 170 km away. Check current status of Warangal's Mamnoor airport.",
      ],
      expenses: [
        "Budget traveller: about ₹1,200 to ₹1,800 per day.",
        "Comfortable traveller: about ₹3,000 to ₹4,500 per day, including a cab for Ramappa.",
        "Monument entry fees are small: usually ₹25 to ₹50 for Indian citizens.",
      ],
      tips: [
        "Start the fort visit early: there is very little shade.",
        "Hire a guide at Ramappa; the sculptures make far more sense with a story.",
        "Carry water and a hat; sturdy shoes help on uneven stone.",
        "Ramappa is quietest on weekday mornings.",
      ],
    },
    basic: [
      ["how_to_reach", "Getting to Warangal cheaply", "From Hyderabad, buses (Express) cost ₹150 to ₹250 and trains ₹70 to ₹350 depending on class. Warangal and Kazipet stations are 10 to 15 minutes apart. From Delhi, Chennai or Vijayawada, take a train on the main trunk line; Sleeper ₹450 to ₹800."],
      ["bus", "Buses in and around Warangal", "TSRTC city buses cover Hanamkonda, Kazipet and Warangal for ₹10 to ₹30. Buses to Palampet (Ramappa) run several times a day from Hanamkonda bus stand for about ₹60 to ₹90 (1.5 hours); check the last return bus before you go."],
      ["train", "Trains from Hyderabad and beyond", "Many express trains stop at Warangal (WL): Hyderabad to Warangal in 2 to 2.5 hours. Sleeper fare about ₹165, 3AC about ₹480. Kazipet Junction is the alternative stop and is closer to Hanamkonda."],
      ["places", "Basic list of places to visit", "Warangal Fort (entry ₹25), Thousand Pillar Temple (free), Bhadrakali Temple (free), Kakatiya Musical Garden, Warangal Fort Museum. Ramappa is the day-trip star. Total sight fees for two days are under ₹200."],
      ["expenses", "Basic expense estimate", "Two days on a budget, per person: transport ₹700 to ₹1,000, lodge ₹1,000 to ₹1,600 (₹600 to ₹1,000 a night), food ₹500 to ₹800, entry ₹100. Total roughly ₹2,500 to ₹3,500."],
      ["itinerary", "Basic 2-day itinerary", "Day 1: Warangal Fort and museum (morning), Thousand Pillar Temple (afternoon), Bhadrakali Lake at sunset.\nDay 2: Bus to Palampet for Ramappa Temple, return by evening."],
      ["other", "Budget travel tips", "Try Telangana meals: jonna rotte (sorghum flatbread) and sarva pindi are local. Buy an early train ticket back to Hyderabad; evening services fill. Water at the fort is limited: carry your own."],
    ],
    premium: [
      ["hotel", "Better hotels in Hanamkonda and Warangal", "Mid-range business hotels in Hanamkonda and Warangal cost ₹2,000 to ₹3,500 a night with breakfast. Telangana Tourism (Haritha) properties offer clean rooms at reasonable rates and are also at Laknavaram. Book AC rooms in summer."],
      ["bike_rental", "Bike rental", "Rental scooters and bikes are limited but available around Hanamkonda for ₹400 to ₹700 a day; ask your hotel to arrange one. Helmets are compulsory; carry a licence. The road to Ramappa is good but has heavy trucks on some stretches."],
      ["local_transport", "Car and cab information", "Self-drive from Hyderabad takes about 3 hours on a four-lane highway. In Warangal, local cabs to Ramappa and back cost about ₹2,200 to ₹3,000 for a full day. Fuel stations are frequent on the highway. Park at the fort's designated lot."],
      ["restaurant", "Better restaurants", "Hanamkonda and Warangal have good Telangana and Hyderabadi-style places; expect ₹250 to ₹500 per person for a full meal, and ₹300 to ₹600 for biryani-style dinners. Ask locals for the best Sunday mutton curry and Telangana special meals."],
      ["itinerary", "Detailed 3-day itinerary", "Day 1: 7:30 am Warangal Fort and museum, lunch, 3 pm Thousand Pillar Temple, 5 pm Bhadrakali Lake.\nDay 2: 8 am cab to Ramappa (1.5 h), guide tour, lunch at Palampet, Ramappa Lake in the afternoon, back by 6 pm.\nDay 3: Laknavaram Lake and suspension bridge, boating, return to Hyderabad."],
      ["expenses", "Detailed estimate: comfortable trip", "Per person for 3 days: stay ₹5,000 to ₹8,000, cab ₹3,000 to ₹4,500 (shared), food ₹1,800 to ₹2,500, entry and boating ₹600. Total roughly ₹10,000 to ₹15,000."],
      ["other", "Extra recommendations", "Visit Pakhal Lake (about 50 km) for birdwatching. Sammakka Sarakka Jatara at Medaram is held every two years and draws millions of pilgrims: book far ahead if you plan to attend."],
    ],
    ultimate: [
      ["flight", "Flights to Warangal", "Fly to Hyderabad (HYD), then drive 3 hours. Typical one-way fares: Delhi ₹3,500 to ₹7,500, Mumbai ₹2,800 to ₹5,500, Bengaluru ₹2,200 to ₹4,500, Chennai ₹2,500 to ₹5,000. Airport to Warangal by taxi is ₹4,000 to ₹5,500 one-way. Check whether the Warangal (Mamnoor) airport has commercial service on your date."],
      ["hotel", "Premium stays", "Warangal has limited luxury options; the best 4-star hotels are in Hanamkonda (₹4,500 to ₹8,000). For a true luxury base, stay in Hyderabad (for example ITC Kakatiya or Taj Falaknuma Palace, from about ₹10,000 to ₹30,000) and make Warangal a day trip with a chauffeur.", "Book on the hotel's official website."],
      ["car_rental", "Chauffeur-driven car rental", "Hyderabad to Warangal round trip with a sedan: ₹5,000 to ₹6,500. Two-day Warangal, Ramappa and Laknavaram package: ₹3,500 to ₹4,500 a day for a sedan, ₹5,500 to ₹7,000 for an SUV. Ask for a driver who knows the Ramappa route.", "Book through a licensed tourist-taxi operator."],
      ["guide", "Professional guides", "Licensed guides are available at Warangal Fort and Ramappa Temple: about ₹800 to ₹1,500 for a 2-hour tour in English or Hindi. Ask at the ticket counter or through Telangana Tourism. A good guide explains the floating-brick roof and the dance sculptures.", "Telangana Tourism / ticket counter."],
      ["restaurant", "Premium dining", "In Hanamkonda, hotel restaurants serve refined Telangana and Andhra menus at ₹700 to ₹1,500 per person. For a special dinner, return to Hyderabad and try a Nizami-style tasting menu (₹2,000 to ₹4,000)."],
      ["itinerary", "Detailed day-by-day itinerary (3 days)", "Day 1: Fly to Hyderabad, car to Warangal (arrive 1 pm), Warangal Fort golden-hour visit, Thousand Pillar Temple.\nDay 2: 8 am drive to Ramappa, private guide, Ramappa Lake, Laknavaram sunset.\nDay 3: Bhadrakali Temple morning, Pakhal Lake, drive back to Hyderabad, flight out."],
      ["expenses", "Complete trip cost (3 days, per person, from a metro)", "Return flight ₹6,000 to ₹12,000; car with driver ₹8,000 to ₹11,000 (split among 2 to 4); hotel ₹8,000 to ₹15,000; food ₹3,000 to ₹5,000; guides and entry ₹2,000. Total roughly ₹25,000 to ₹45,000."],
      ["other", "Premium recommendations", "Book the guide for Ramappa in advance for peak season. Go at sunrise to the fort for photography. Pair with Hyderabad's Charminar and Golconda Fort for a heritage week."],
    ],
    rates: [
      ["basic", "Bus: Hyderabad to Warangal", 200, "per person", "Express bus, about 3 hours"],
      ["basic", "Train: Hyderabad to Warangal (sleeper)", 165, "per person", "About 2 to 2.5 hours"],
      ["basic", "Bus: Hanamkonda to Palampet (Ramappa)", 75, "per person", "Check return times"],
      ["basic", "Local auto-rickshaw", 50, "per short ride", "Bargain before you go"],
      ["basic", "Telangana meals", 130, "per meal", "Local restaurant"],
      ["premium", "Hotel, Hanamkonda (AC)", 2800, "per night", "Breakfast included"],
      ["premium", "Scooter rental", 500, "per day", "Ask your hotel"],
      ["premium", "Cab: Warangal to Ramappa and back", 2600, "per day", "Sedan, about 150 km"],
      ["premium", "Dinner for two", 1200, "for two", "Mid-range restaurant"],
      ["ultimate", "Flight: Delhi to Hyderabad", 5500, "one way", "Typical fare"],
      ["ultimate", "Premium hotel (Hyderabad 5-star)", 13000, "per night", "Luxury base"],
      ["ultimate", "Chauffeur-driven SUV", 6000, "per day", "About 250 km included"],
      ["ultimate", "Licensed guide", 1200, "per 2 hours", "Warangal Fort or Ramappa"],
    ],
  },

  // ──────────────────────────────────────────────────────────
  {
    slug: "goa",
    title: "Goa",
    location: "Goa, India",
    summary: "Sun, sand and shacks, plus Portuguese churches, spice farms and a waterfall.",
    cover: "/uploads/travel-goa.jpg",
    blog: {
      title: "Goa – Beaches, Nightlife and Adventure",
      sub: "Beach & Islands",
      heading: "1. Goa – Beaches, Nightlife and Adventure",
      intro: "India's smallest state has 100 km of coastline and two personalities. North Goa is beach parties, watersports and flea markets; South Goa is quieter coves, resorts and Portuguese-era villages. Old Goa and Fontainhas add churches, culture and colour.",
      about: "The season runs from November to February (cool, dry, busy) and stays good until March. May to September is monsoon: beaches close for swimming, but green landscapes and low prices draw a different crowd. Konkani, English and Hindi are all spoken.",
      places: [
        ["Baga, Calangute and Anjuna beaches", "Lively North Goa beaches with watersports, shacks and the Saturday night market at Arpora."],
        ["Vagator and Chapora Fort", "Red cliffs, sunset parties and the fort made famous by a Bollywood film."],
        ["Old Goa", "UNESCO churches including the Basilica of Bom Jesus, and the Se Cathedral."],
        ["Palolem and Agonda (South Goa)", "Crescent beaches with calm water, yoga retreats and quiet cafes."],
        ["Dudhsagar Falls", "A four-tier waterfall reached by jeep from Kulem (closed during heavy monsoon)."],
      ],
      reach: [
        "By air: Dabolim (GOI) in the south and Manohar International at Mopa (GOX) in the north.",
        "By train: Madgaon (MAO) and Thivim are on the Konkan Railway; Vande Bharat runs from Mumbai.",
        "By road: Overnight buses from Mumbai, Pune and Bengaluru. Roads are good from Belagavi and Pune.",
      ],
      expenses: [
        "Budget traveller: about ₹1,800 to ₹2,500 per day (hostel bed, shack meals, scooter).",
        "Comfortable traveller: about ₹5,000 to ₹8,000 per day (boutique stay, watersports, dinners).",
        "Peak weeks (Christmas to New Year) can double hotel prices.",
      ],
      tips: [
        "Use the government Goa Miles taxi app to avoid inflated fares.",
        "Drive carefully: helmets are mandatory and police check papers.",
        "Outdoor music must stop at 10 pm; some parties move indoors.",
        "Avoid swimming after dark or where red flags are up.",
      ],
    },
    basic: [
      ["how_to_reach", "Reaching Goa on a budget", "Trains and buses are cheapest. Mumbai to Madgaon (Konkan Railway) sleeper is about ₹500 to ₹800; 3AC ₹1,300 to ₹1,900. Overnight buses from Pune ₹800 to ₹1,400, from Mumbai ₹1,000 to ₹1,800, from Bengaluru ₹1,000 to ₹1,800."],
      ["bus", "Local buses", "Kadamba Transport Corporation (KTC) buses link Panjim (Panaji), Margao, Mapusa and the beaches for ₹15 to ₹60. Panjim to Calangute is about ₹25. Last buses to the beaches finish early evening; keep a taxi fallback."],
      ["train", "Trains and stations", "Madgaon (MAO) is the main station for South Goa; Thivim is best for North Goa; Karmali for Old Goa. From Madgaon, a shared bus or pre-paid taxi to Palolem costs ₹100 to ₹900."],
      ["places", "Basic sightseeing", "Baga, Anjuna and Vagator beaches (free), Fort Aguada (small fee), Chapora Fort (free), Old Goa's Bom Jesus (free), Saturday Night Market at Arpora (entry fee). Budget travellers can do all of these by bus and scooter."],
      ["expenses", "Basic expense estimate", "Four days, per person: dorm bed ₹500 to ₹900 a night (₹2,000 to ₹3,600), scooter ₹1,200 to ₹1,600, food ₹1,600 to ₹2,400, fuel and fees ₹700. Total roughly ₹7,000 to ₹9,500."],
      ["itinerary", "Basic 4-day itinerary", "Day 1: Arrive, Calangute and Baga beaches, Baga sunset.\nDay 2: Fort Aguada, Candolim, Anjuna beach, Saturday Night Market.\nDay 3: Old Goa churches, Panjim's Fontainhas walk.\nDay 4: Vagator sunrise, Chapora Fort, depart."],
      ["other", "Budget tips", "Eat where locals eat: fish thali (₹150 to ₹250) beats beach-shack prices. Bargain at flea markets. Book dorms early for December. Carry sun protection and a reusable water bottle."],
    ],
    premium: [
      ["hotel", "Better stays", "Boutique guesthouses in Assagao, Anjuna and Palolem are ₹3,500 to ₹6,500 a night; beach-facing 3-star resorts ₹4,500 to ₹8,000 off-peak. Pick a stay near the beach you plan to spend time at, not just 'in Goa'."],
      ["bike_rental", "Scooter and bike rental", "Scooter ₹300 to ₹500 a day (Activa-type), Royal Enfield ₹700 to ₹1,200 a day. Rent from a shop with clear terms and helmets; deposits of ₹1,000 to ₹3,000. Fines for no helmet or licence are strict."],
      ["local_transport", "Car information", "Self-drive hatchbacks run ₹1,800 to ₹2,800 a day plus fuel; toll-free on most Goa roads. Parking at Baga and Calangute fills by noon in season. Pre-book taxis via the Goa Miles app or your hotel."],
      ["restaurant", "Better restaurants", "Fisherman's Wharf (Panjim/Cavelossim), Britto's in Baga and Vinayak (Assagao) are favourites for seafood; Gunpowder (Assagao) for South Indian; Thalassa (Vagator) for Greek dinners at sunset. Expect ₹600 to ₹1,500 per person."],
      ["itinerary", "Detailed 4-day itinerary", "Day 1: Arrive, check in at Assagao, 5 pm Baga beach, 8 pm dinner at Britto's or nearby.\nDay 2: 9 am Fort Aguada, lunch in Candolim, watersports at Calangute (parasailing about ₹1,200), Arpora night market.\nDay 3: 8 am Old Goa churches, Fontainhas, Panjim dinner cruise on the Mandovi.\nDay 4: Spice plantation tour (₹500 to ₹800 with lunch), Vagator sunset."],
      ["expenses", "Detailed estimate: comfortable trip", "Per person for 4 days: stay ₹14,000 to ₹22,000 (twin share), scooter or cab ₹3,000 to ₹5,000, food ₹4,000 to ₹6,000, watersports and entry ₹3,000 to ₹5,000. Total roughly ₹22,000 to ₹35,000."],
      ["other", "Extra recommendations", "Visit Dudhsagar Falls by jeep from Kulem (about ₹600 to ₹800 per person; closed in monsoon). Take a sunrise dolphin cruise from Sinquerim (about ₹500 to ₹800). Try a cooking class in Assagao."],
    ],
    ultimate: [
      ["flight", "Flights to Goa", "Two airports: Mopa (GOX) for North Goa, Dabolim (GOI) for the south. Typical one-way fares: Delhi ₹4,500 to ₹9,500, Mumbai ₹2,500 to ₹5,000, Bengaluru ₹2,500 to ₹5,500, Hyderabad ₹3,000 to ₹6,000. Airport to Baga: about ₹1,000 (GOI) to ₹1,800 (GOX) by taxi."],
      ["hotel", "Premium hotels", "Taj Fort Aguada Resort & Spa (Candolim, about ₹12,000 to ₹30,000), W Goa (Vagator, about ₹15,000 to ₹35,000), The Leela Goa (Cavelossim, about ₹14,000 to ₹32,000). Book directly for best rates.", "Book on the hotel's official website."],
      ["car_rental", "Chauffeur-driven car rental", "Sedan with driver ₹3,000 to ₹4,000 a day; SUV ₹4,500 to ₹6,500 a day. Airport transfers are ₹1,000 to ₹2,500. Half-day North Goa sightseeing about ₹1,800 to ₹2,500.", "Licensed tourist-taxi operator or your hotel."],
      ["guide", "Local and professional guides", "Old Goa heritage guide ₹800 to ₹1,500 per half-day; Fontainhas walking tour ₹500 to ₹1,000 per person; spice plantation guided tours are typically included in the entry price. Ask for a Goa Tourism-registered guide.", "Goa Tourism Development Corporation."],
      ["restaurant", "Premium restaurants", "Fine-dining tasting menus in Panjim and Assagao ₹2,000 to ₹4,500 per person; beach clubs at Vagator and Ashwem for sunset (₹1,500 to ₹3,500 per person). Book a table before 7 pm to get a sunset view."],
      ["itinerary", "Detailed 5-day luxury itinerary", "Day 1: Arrive Mopa, check in at a beachfront resort, sunset cruise.\nDay 2: Old Goa with a guide, lunch in Panjim, spa afternoon.\nDay 3: Watersports morning, Chapora Fort sunset, dinner at Vagator beach club.\nDay 4: Drive south, Palolem and Agonda beaches, private villa stay.\nDay 5: Spice farm brunch, Dabolim flight out."],
      ["expenses", "Complete trip cost (5 days, per person, from a metro)", "Return flight ₹7,000 to ₹15,000; hotels ₹55,000 to ₹95,000; chauffeur car ₹15,000 to ₹22,000; food ₹12,000 to ₹20,000; activities and guides ₹6,000 to ₹10,000. Total roughly ₹95,000 to ₹1,60,000."],
      ["other", "Premium recommendations", "Book a private yacht for sunset (₹12,000 to ₹35,000). Visit Grande Island for scuba (about ₹1,800 to ₹3,500). Choose a villa with a private pool in Assagao for groups."],
    ],
    rates: [
      ["basic", "Bus: Panjim to Calangute", 25, "per person", "KTC bus"],
      ["basic", "Train: Mumbai to Madgaon (sleeper)", 600, "per person", "Konkan Railway"],
      ["basic", "Dorm bed", 700, "per night", "Hostel, off-peak"],
      ["basic", "Fish thali", 200, "per meal", "Local restaurant"],
      ["basic", "Local taxi (short ride)", 300, "per ride", "Use Goa Miles"],
      ["premium", "Boutique stay (Assagao)", 5000, "per night", "Breakfast included"],
      ["premium", "Scooter rental", 400, "per day", "Deposit and ID"],
      ["premium", "Royal Enfield rental", 1000, "per day", "Helmet included"],
      ["premium", "Dinner for two (seafood)", 2200, "for two", "Beach restaurant"],
      ["premium", "Parasailing", 1200, "per person", "Calangute/Baga"],
      ["ultimate", "Flight: Bengaluru to Goa", 4000, "one way", "Typical fare"],
      ["ultimate", "5-star resort", 18000, "per night", "Beachfront"],
      ["ultimate", "Chauffeur-driven sedan", 3500, "per day", "Full day"],
      ["ultimate", "Old Goa heritage guide", 1200, "per half-day", "Registered guide"],
    ],
  },

  // ──────────────────────────────────────────────────────────
  {
    slug: "manali",
    title: "Manali",
    location: "Himachal Pradesh, India",
    summary: "Snow peaks, pine forests, hot springs and paragliding at the top of the Kullu Valley.",
    cover: "/uploads/travel-manali.jpg",
    blog: {
      title: "Manali – Mountains and Adventure",
      sub: "Adventure",
      heading: "1. Manali – Mountains and Adventure",
      intro: "Manali sits at 2,050 metres on the banks of the Beas, framed by Himalayan peaks and deodar forests. It is a base for treks, paragliding, skiing and road trips into Lahaul and Spiti, and it is just as good for a few slow days of cafe hopping in Old Manali.",
      about: "Summer (April to June) is mild and busy; monsoon (July to September) brings landslides on the highway; winter (December to February) brings snow, skiing and road closures. Rohtang Pass and the higher roads are usually open only from late May to October. Hindi, Pahari and English are widely spoken.",
      places: [
        ["Hadimba Temple", "A wooden pagoda temple in a cedar forest, dedicated to Hidimba Devi."],
        ["Old Manali", "Cafes, hostels, riverside walks and a relaxed traveller scene."],
        ["Solang Valley", "Paragliding, zorbing and skiing, about 14 km from town."],
        ["Atal Tunnel and Sissu", "A 9 km tunnel to Lahaul and the snowy landscapes beyond."],
        ["Naggar Castle", "A 500-year-old castle with views of the valley and the Roerich Art Gallery."],
      ],
      reach: [
        "By road: Delhi to Manali is about 540 km (12 to 14 hours); Chandigarh to Manali about 310 km (8 to 9 hours). HRTC and private Volvo buses run overnight.",
        "By air: Bhuntar (Kullu-Manali, KUU) is about 50 km away, with limited flights. Chandigarh (IXC) is the busier alternative.",
        "By train: There is no railhead in Manali. The nearest broad-gauge stations are Chandigarh and Ambala.",
      ],
      expenses: [
        "Budget traveller: about ₹1,500 to ₹2,200 per day (hostel dorm, local meals, buses).",
        "Comfortable traveller: about ₹4,000 to ₹6,500 per day (hotel, cab, adventure).",
        "Winter and May to June are peak season; hotel prices can double.",
      ],
      tips: [
        "Check road status before travelling; snow and landslides can close highways.",
        "Acclimatise: do easy walks on day one if heading above 3,000 metres.",
        "Rohtang Pass needs an online permit and is closed in winter.",
        "Carry warm layers even in summer; nights are cold.",
      ],
    },
    basic: [
      ["how_to_reach", "Reaching Manali on a budget", "HRTC ordinary and semi-deluxe buses from Delhi (ISBT Kashmere Gate) cost ₹800 to ₹1,300; Volvo AC ₹1,300 to ₹2,000. Trains go to Chandigarh (₹400 to ₹900 from Delhi), then a Chandigarh to Manali bus ₹600 to ₹1,000. Overnight buses save a hotel night."],
      ["bus", "Local buses", "Local HRTC buses connect Manali, Old Manali, Solang, Naggar and Kullu for ₹15 to ₹60. Manali to Kullu ₹40 to ₹60 (1.5 hours). Buses to Kasol usually change at Bhuntar."],
      ["train", "Trains nearby", "Nearest broad-gauge stations: Chandigarh (about 310 km), Ambala, and Kiratpur Sahib. From Chandigarh take a bus (8 to 9 hours). The narrow-gauge line to Joginder Nagar is a long way from Manali."],
      ["places", "Basic places to visit", "Hadimba Temple (free), Manu Temple, Vashisht hot springs (free), Jogini Falls trek (2 to 3 hours round trip), Old Manali cafes, Mall Road. Naggar Castle has a small entry fee."],
      ["expenses", "Basic expense estimate", "Four days, per person: bus travel from Delhi ₹2,000 to ₹3,500, dorm ₹500 to ₹900 a night (₹2,000 to ₹3,600), food ₹1,600 to ₹2,400, local buses and entry ₹500. Total roughly ₹6,500 to ₹10,000."],
      ["itinerary", "Basic 4-day itinerary", "Day 1: Arrive, Mall Road and Hadimba Temple.\nDay 2: Old Manali, Jogini Falls trek, Vashisht hot springs.\nDay 3: Bus to Naggar Castle and back.\nDay 4: Buffer day or Solang Valley by local bus, then depart."],
      ["other", "Budget tips", "Eat siddu, dhaam and momos in local places for ₹100 to ₹250. Book hostels for December to January early. Share taxis to Solang. Carry cash: ATMs can be crowded."],
    ],
    premium: [
      ["hotel", "Better stays", "Mid-range hotels on Hadimba Road and in Old Manali: ₹2,500 to ₹5,000 a night off-peak, ₹4,500 to ₹8,000 in peak season. Riverside cottages and homestays are ₹2,000 to ₹4,000. Ask for heaters in winter."],
      ["bike_rental", "Bike rental", "Scooters ₹700 to ₹1,000 per day; Royal Enfield (350cc) ₹1,200 to ₹1,800 per day; long-term discounts for 3+ days. Deposits ₹2,000 to ₹5,000. Riders must have a licence and helmets. Avoid night riding on the Atal Tunnel road."],
      ["local_transport", "Car and self-drive information", "Delhi to Manali is 12 to 14 hours by car via Chandigarh and Mandi. Tunnel toll is about ₹80 to ₹100 one way. In winter, carry snow chains and check road status. Parking in Old Manali is tight: use the paid lots near the bridge."],
      ["restaurant", "Better restaurants", "Old Manali has excellent cafes for trout, wood-fired pizza and Himachali thali (₹350 to ₹700 per person). Try local dishes: siddu, chana madra, trout fish. Book weekend dinners early in season."],
      ["itinerary", "Detailed 4-day itinerary", "Day 1: Arrive, check in, 4 pm Hadimba Temple, evening at Old Manali.\nDay 2: 8 am Solang Valley (paragliding about ₹2,500 to ₹3,500), lunch, Atal Tunnel to Sissu.\nDay 3: Naggar Castle, Roerich Gallery, Kullu handloom shops.\nDay 4: Vashisht hot springs and depart."],
      ["expenses", "Detailed estimate: comfortable trip", "Per person for 4 days: stay ₹12,000 to ₹20,000 (twin share), cab or bike ₹4,000 to ₹6,000, food ₹3,500 to ₹5,000, adventure ₹3,000 to ₹5,000, entry fees ₹500. Total roughly ₹20,000 to ₹33,000."],
      ["other", "Extra recommendations", "Take a day trip to Kasol and Manikaran (about 75 km). Attempt an easy trek to Beas Kund or Hampta Pass with a guide in season. Spend a morning at Solang Valley before crowds arrive."],
    ],
    ultimate: [
      ["flight", "Flights to Manali", "Fly to Bhuntar (KUU) on limited seasonal services, or to Chandigarh (IXC), then drive 8 hours. Typical one-way fares: Delhi to Bhuntar ₹4,000 to ₹8,500 (when operated), Delhi to Chandigarh ₹3,000 to ₹6,000. A chauffeured car from Chandigarh is ₹8,000 to ₹11,000; from Bhuntar about ₹1,800 to ₹2,500."],
      ["hotel", "Premium hotels", "The Himalayan (Hadimba Road, about ₹9,000 to ₹22,000), Span Resort & Spa (Kullu-Manali road, about ₹8,000 to ₹18,000). Look for rooms with balcony views of the Beas. Confirm heating and power backup.", "Book on the hotel's official website."],
      ["car_rental", "Chauffeur-driven car rental", "Delhi to Manali one way (sedan) ₹9,000 to ₹13,000; SUV ₹13,000 to ₹18,000. Local sightseeing per day: sedan ₹3,000 to ₹4,500, SUV ₹4,500 to ₹7,000. Winter needs a 4x4 or driver experienced with snow.", "Licensed HP tourist-taxi operator."],
      ["guide", "Professional and trek guides", "Registered trek guides: ₹2,000 to ₹3,500 per day (Hampta Pass, Beas Kund). Paragliding pilots are certified through the local association: choose an operator with a government-registered pilot and insurance. Local sightseeing guide ₹1,000 to ₹1,800 per half-day.", "HP Tourism / local adventure associations."],
      ["restaurant", "Premium restaurants", "Chef-led tasting menus with Himachali specialities at luxury hotels: ₹1,800 to ₹3,500 per person. Riverside dining in Old Manali at the better cafes ₹800 to ₹1,500 per person."],
      ["itinerary", "Detailed 5-day luxury itinerary", "Day 1: Fly to Chandigarh, car to Manali (arrive evening).\nDay 2: Hadimba Temple, Old Manali, spa evening.\nDay 3: Solang Valley paragliding, Atal Tunnel, Sissu.\nDay 4: Naggar Castle, Kasol or a private riverside picnic.\nDay 5: Morning at the hot springs, drive back to Chandigarh, fly out."],
      ["expenses", "Complete trip cost (5 days, per person, from a metro)", "Return flight ₹6,000 to ₹14,000; hotels ₹45,000 to ₹80,000; chauffeur cars ₹20,000 to ₹28,000; food ₹10,000 to ₹15,000; guides and adventure ₹8,000 to ₹14,000. Total roughly ₹90,000 to ₹1,50,000."],
      ["other", "Premium recommendations", "Arrange a private trek with a registered guide and porter. Visit Naggar on a sunset walk. Book a heated glass-top cottage in winter. Avoid unlicensed adventure operators."],
    ],
    rates: [
      ["basic", "Bus: Delhi to Manali (HRTC ordinary)", 1100, "per person", "About 12 to 14 hours"],
      ["basic", "Bus: Manali to Solang", 40, "per person", "Local HRTC bus"],
      ["basic", "Dorm bed (Old Manali)", 700, "per night", "Off-peak"],
      ["basic", "Local meals (thali)", 180, "per meal", "Local restaurant"],
      ["basic", "Share taxi (local)", 150, "per person", "Manali to Naggar"],
      ["premium", "Mid-range hotel", 3800, "per night", "Twin, breakfast"],
      ["premium", "Scooter rental", 850, "per day", "Deposit and ID"],
      ["premium", "Royal Enfield rental", 1500, "per day", "Helmet included"],
      ["premium", "Paragliding (Solang)", 2800, "per person", "10 to 15 minutes"],
      ["premium", "Dinner for two", 1500, "for two", "Old Manali cafe"],
      ["ultimate", "Flight: Delhi to Chandigarh", 4000, "one way", "Typical fare"],
      ["ultimate", "Premium hotel", 14000, "per night", "Valley view"],
      ["ultimate", "Chauffeur-driven SUV (local)", 5500, "per day", "8 hours"],
      ["ultimate", "Trek guide", 2500, "per day", "Registered guide"],
    ],
  },

  // ──────────────────────────────────────────────────────────
  {
    slug: "jaipur",
    title: "Jaipur",
    location: "Rajasthan, India",
    summary: "The Pink City: hilltop forts, royal palaces, bazaars and Rajasthani food.",
    cover: "/uploads/travel-jaipur.jpg",
    blog: {
      title: "Jaipur – The Pink City",
      sub: "City Breaks",
      heading: "1. Jaipur – The Pink City",
      intro: "Founded in 1727 by Maharaja Sawai Jai Singh II, Jaipur is Rajasthan's capital and the anchor of the Golden Triangle. Forts stand on the hills, the old city glows terracotta pink, and the bazaars are among the best in India for textiles, jewellery and blue pottery.",
      about: "Winter (October to March) is the ideal time. Summers can cross 45°C. The old city is best explored on foot or by auto-rickshaw; the forts are a short drive away. Hindi, Rajasthani and English are widely understood.",
      places: [
        ["Amber Fort", "A hilltop fort-palace with mirrored halls, about 11 km from the city."],
        ["Hawa Mahal", "The 'Palace of Winds' with its pink sandstone honeycomb facade."],
        ["City Palace and Jantar Mantar", "A royal residence and an UNESCO-listed astronomical observatory."],
        ["Nahargarh and Jaigarh Forts", "Sunset views over the city and the world's largest cannon on wheels."],
        ["Johari Bazaar and Bapu Bazaar", "Jewellery, textiles, mojaris and block-print fabric."],
      ],
      reach: [
        "By air: Jaipur International Airport (JAI) has direct flights from most major Indian cities.",
        "By train: Jaipur Junction (JP) is well connected to Delhi (4.5 to 5 hours by Shatabdi or Vande Bharat), Mumbai and Ahmedabad.",
        "By road: Delhi to Jaipur is about 280 km (5 to 6 hours) on NH48; RSRTC and private AC buses run all day.",
      ],
      expenses: [
        "Budget traveller: about ₹1,500 to ₹2,200 per day.",
        "Comfortable traveller: about ₹4,000 to ₹6,000 per day.",
        "A composite ticket covers several monuments for two days at about ₹300 to ₹350 for Indian citizens.",
      ],
      tips: [
        "Start with Amber Fort at opening time to beat crowds and heat.",
        "Prefer walking or vehicle tours; consider skipping elephant rides for animal welfare reasons.",
        "Bargain politely in bazaars: start at half the quoted price.",
        "Check closing days: some museums close one day a week.",
      ],
    },
    basic: [
      ["how_to_reach", "Reaching Jaipur cheaply", "From Delhi, the cheapest option is an RSRTC ordinary bus for ₹400 to ₹600, or a general or sleeper train ticket for ₹200 to ₹400 (4.5 to 6 hours). AC buses and trains cost ₹600 to ₹1,000. From Mumbai, take an overnight train (Sleeper ₹500 to ₹800)."],
      ["bus", "Buses in Jaipur", "City buses cost ₹10 to ₹30 and reach Amber, Hawa Mahal and the bus stands. Sindhi Camp bus stand is the main hub. For Amber Fort, a city bus from Badi Chaupar is about ₹20 and takes 30 to 40 minutes."],
      ["train", "Trains", "Jaipur Junction (JP) has frequent trains to Delhi, Ajmer, Ahmedabad and Mumbai. Delhi to Jaipur Shatabdi/Vande Bharat chair car about ₹850 to ₹1,700. General and sleeper on other express trains costs less."],
      ["places", "Basic places to visit", "Hawa Mahal (₹50), Jantar Mantar (₹50), City Palace (about ₹200), Amber Fort (₹100), Albert Hall Museum (₹40 to ₹50), Jal Mahal (view free), Patrika Gate (free). A composite ticket may reduce total cost for several monuments."],
      ["expenses", "Basic expense estimate", "Three days on a budget, per person: transport ₹600 to ₹1,000 (bus/train), stay ₹1,200 to ₹2,400 (dorm or lodge at ₹400 to ₹800), food ₹900 to ₹1,500, entry ₹500 to ₹700, local transport ₹400. Total roughly ₹4,000 to ₹6,000."],
      ["itinerary", "Basic 3-day itinerary", "Day 1: Hawa Mahal, City Palace, Jantar Mantar, Johari Bazaar.\nDay 2: Amber Fort in the morning, Jal Mahal, Nahargarh sunset.\nDay 3: Albert Hall, Bapu Bazaar shopping, depart."],
      ["other", "Budget tips", "Eat pyaaz kachori and lassi for breakfast (₹60 to ₹120). Take shared autos on fixed routes. Avoid touts offering 'free' shopping tours."],
    ],
    premium: [
      ["hotel", "Better stays", "Heritage haveli hotels and good 3-star hotels: ₹3,000 to ₹6,500 a night with breakfast; boutique havelis in the old city ₹4,500 to ₹9,000. Choose one with a rooftop for city views."],
      ["bike_rental", "Scooter and bike rental", "Scooters rent for ₹400 to ₹600 a day; bikes ₹700 to ₹1,200. Amber Fort road can be busy; ride carefully. Carry ID and a licence; helmets are mandatory."],
      ["local_transport", "Car information", "Delhi to Jaipur by self-drive takes 5 to 6 hours on NH48 with a toll of roughly ₹500 to ₹700. Parking in the old city is limited; use paid lots near Hawa Mahal or Johari Bazaar. Rental hatchbacks ₹1,800 to ₹2,800 a day."],
      ["restaurant", "Better restaurants", "Laxmi Misthan Bhandar (LMB) for sweets and thali, Rawat Mishthan Bhandar for pyaaz kachori, Chokhi Dhani for a village-style dinner with folk performances (₹900 to ₹1,300). Expect ₹400 to ₹900 per person."],
      ["itinerary", "Detailed 3-day itinerary", "Day 1: 9 am Amber Fort, 12 pm Panna Meena Ka Kund, lunch, 3 pm Jal Mahal, 5 pm Nahargarh sunset.\nDay 2: 9 am City Palace, Jantar Mantar, Hawa Mahal, Johari Bazaar shopping, dinner at LMB.\nDay 3: Albert Hall, Chokhi Dhani in the evening."],
      ["expenses", "Detailed estimate: comfortable trip", "Per person for 3 days: stay ₹9,000 to ₹15,000, cab and auto ₹2,500 to ₹4,000, food ₹2,400 to ₹3,600, entry ₹600 to ₹1,000, shopping extra. Total roughly ₹15,000 to ₹24,000."],
      ["other", "Extra recommendations", "Visit Sanganer for block printing workshops, Galtaji (Monkey Temple) at sunset and Sisodia Rani Garden. Buy from government emporiums (Rajasthali) for fixed prices."],
    ],
    ultimate: [
      ["flight", "Flights to Jaipur", "Direct flights from Delhi (₹3,000 to ₹6,500), Mumbai (₹3,500 to ₹7,500), Bengaluru (₹4,500 to ₹9,000), Kolkata (₹4,500 to ₹9,000). The airport is about 12 km from the old city (₹400 to ₹700 by taxi). Book 3 to 4 weeks ahead."],
      ["hotel", "Premium hotels", "Rambagh Palace (Taj, about ₹28,000 to ₹80,000), Taj Jai Mahal Palace (about ₹12,000 to ₹30,000), The Oberoi Rajvilas (about ₹35,000 to ₹80,000), Samode Haveli (about ₹8,000 to ₹18,000). Prices peak from November to February.", "Book on the hotel's official website."],
      ["car_rental", "Chauffeur-driven car rental", "Sedan with driver ₹2,500 to ₹3,500 a day (about 8 hours, 80 km local); SUV ₹4,000 to ₹6,000. Delhi to Jaipur one way: sedan ₹4,500 to ₹6,000; SUV ₹7,000 to ₹9,000.", "Licensed tourist-taxi operator."],
      ["guide", "Local and professional guides", "Government-approved guides at Amber Fort, City Palace and other monuments: ₹500 to ₹1,000 for a 2-hour tour in Hindi or English; full-day city guide ₹1,500 to ₹2,500. Ask for an official guide card. Book in advance for peak season.", "Rajasthan Tourism / monument ticket counters."],
      ["restaurant", "Premium restaurants", "Suvarna Mahal at Rambagh Palace, rooftop fine dining in old-city havelis and 1135 AD at Amber: ₹2,000 to ₹5,000 per person. Book two days ahead in winter."],
      ["itinerary", "Detailed 4-day luxury itinerary", "Day 1: Arrive, check in at a palace hotel, sunset over the city.\nDay 2: Amber Fort with a guide at 9 am, lunch at 1135 AD, City Palace, Jantar Mantar, Hawa Mahal.\nDay 3: Sanganer block-printing workshop, Rajasthali shopping, private dinner at a haveli.\nDay 4: Spa morning, Nahargarh sunrise, depart."],
      ["expenses", "Complete trip cost (4 days, per person, from a metro)", "Return flight ₹7,000 to ₹14,000; hotels ₹60,000 to ₹1,20,000; chauffeur car ₹12,000 to ₹16,000; food ₹10,000 to ₹18,000; guides and entry ₹4,000 to ₹7,000. Total roughly ₹95,000 to ₹1,75,000."],
      ["other", "Premium recommendations", "Take a hot-air balloon ride over Amber (about ₹12,000 to ₹15,000, seasonal) or a vintage car tour. Shop for gems at reputed showrooms with certified valuations."],
    ],
    rates: [
      ["basic", "Bus: Delhi to Jaipur (RSRTC ordinary)", 500, "per person", "About 5 to 6 hours"],
      ["basic", "Train: Delhi to Jaipur (sleeper)", 250, "per person", "Check timings"],
      ["basic", "City bus: Badi Chaupar to Amber", 20, "per person", "About 30 to 40 minutes"],
      ["basic", "Pyaaz kachori + lassi", 120, "per person", "Breakfast"],
      ["basic", "Auto-rickshaw (old city)", 100, "per short ride", "Agree fare first"],
      ["premium", "Haveli hotel", 5500, "per night", "Breakfast included"],
      ["premium", "Scooter rental", 500, "per day", "Deposit and ID"],
      ["premium", "Chokhi Dhani dinner", 1100, "per person", "Village-style"],
      ["premium", "Cab: Amber and forts", 1800, "per day", "Local sightseeing"],
      ["ultimate", "Flight: Delhi to Jaipur", 4500, "one way", "Typical fare"],
      ["ultimate", "Palace hotel", 35000, "per night", "Peak season"],
      ["ultimate", "Chauffeur-driven sedan", 3000, "per day", "About 8 hours"],
      ["ultimate", "Approved monument guide", 800, "per 2 hours", "Amber Fort"],
    ],
  },
];
